### ISSUE TITLE
Unhandled exception. System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by imgfilesbox** [yodadude2003/DATOneArchiver#3]
Hi! Help me please. What am I doing wrong?

F:\Steam\steamapps\common\LEGO Lord of the Rings\translate\Dataonearchive>datonearchiver list -f datfiles\GAME.dat
Reading archive file...
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at QuesoStruct.Types.Collections.Collection`1.get_Item(Int32 index)
   at DATOneArchiver.Archive.WalkEntries(IList`1 blobs, IList`1 entries, Int32 startIdx, Int16 terminator, String dir)
   at DATOneArchiver.Archive.WalkEntries(IList`1 blobs, IList`1 entries, Int32 startIdx, Int16 terminator, String dir)
   at DATOneArchiver.Archive.WalkEntries(IList`1 blobs, IList`1 entries, Int32 startIdx, Int16 terminator, String dir)
   at DATOneArchiver.Archive.WalkEntries(IList`1 blobs, IList`1 entries, Int32 startIdx, Int16 terminator, String dir)
   at DATOneArchiver.Archive.WalkEntries(IList`1 blobs, IList`1 entries, Int32 startIdx, Int16 terminator, String dir)
   at DATOneArchiver.Archive.WalkEntries(IList`1 blobs, IList`1 entries, Int32 startIdx, Int16 terminator, String dir)
   at DATOneArchiver.Archive.WalkEntries(IList`1 blobs, IList`1 entries, Int32 startIdx, Int16 terminator, String dir)
   at DATOneArchiver.Archive.WalkEntries(IList`1 blobs, IList`1 entries, Int32 startIdx, Int16 terminator, String dir)
   at DATOneArchiver.Archive.WalkEntries(IList`1 blobs, IList`1 entries, Int32 startIdx, Int16 terminator, String dir)
   at DATOneArchiver.Archive.WalkEntries(IList`1 blobs, IList`1 entries, Int32 startIdx, Int16 terminator, String dir)
   at DATOneArchiver.Archive.Read()
   at DATOneArchiver.Program.RunList(ListOptions options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at DATOneArchiver.Program.Main(String[] args)

**Comment by IsaMorphic** [comment]
LEGO Lord of the Rings is not a supported game, this tool only supports LSW1 and LSW2, as well as other PS2 era DATs
